# Trust
#### _The weight of words_

On a daily basis, we have to place our trust into many different places, people, things, organizations, businesses, and ourselves. 

- We **trust** that the bank will keep our money safe. We trust that our money will still be there when we come back to withdraw some out.

- We **trust** that our car or whatever means of transportation we are using will get us from one place to another safely. 

- We **trust** that our friends will keep our secrets safe when we share something with them. 

- We **trust** that we will wake up the next morning whenever we go to sleep at night. 

- We **trust** that our lungs will intake air, that our muscles will allow us to move, our brains to keep us thinking, and that our bodies will do its job to keep us alive. 

Trust is a necessary part of living. 
Though once that trust has been broken, it is difficult to rebuild. 

Trust is fragile. Delicate.
It cannot be built through words alone.
It must be supported through one's actions. 

But occasionally, trust placed in words can be set on a pedestal that normally cannot be reached. 
The words “I promise” hold a very heavy meaning.
I do not use it lightly.
I do not pair it with words such as  “always”, “forever”, and “never”
For those adverbs of frequency will not be achieved.

People will hurt you with broken promises and false hope
That is just a part of life. 
But I will not do the same to others. 
I strive not to be what others have done to hurt me. 

Trust is built when one is ready to show their vulnerable side.
Trust is built when the other is respectful of it.
Trust is built when both parties mutually respect and listen to each other. 
